# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: rimseval-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build and test
  build:
    if: github.repository_owner == 'RIMS-Code'
    runs-on: ubuntu-latest

    steps:
    - uses: wntrblm/nox
      with:
        python-versions: "3.8, 3.9, 3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libegl1-mesa
        python -m pip install --upgrade pip
        pip install .[test]
        pip install coveralls
    - name: Run nox
      run: nox
    - name: Re-run coverage and push to coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pytest
        coveralls
